[package]
name = "angicourt"
version = "0.1.0"
authors = ["Axel Magnuson <axelmagn@gmail.com>"]

[dependencies]
piston = "0.31.3"
piston_window = "0.64.0"
find_folder = "0.3.0"
rand = "0.3"
specs = "0.8"
